DROP TABLE SIQUOIA.AUTHENTICATION;
DROP TABLE SIQUOIA.QUESTION;
DROP TABLE SIQUOIA.USERPROFILE;

CREATE TABLE SIQUOIA.AUTHENTICATION(
ID INT NOT NULL AUTO_INCREMENT, 
USERNAME VARCHAR(32),
USERPASSWORD VARCHAR(32),
ADMIN BOOL,
PRIMARY KEY(ID));

CREATE TABLE SIQUOIA.QUESTION(
QID INT NOT NULL AUTO_INCREMENT,
CONTENT VARCHAR(255),
OPTION1 VARCHAR(255),
OPTION2 VARCHAR(255),
OPTION3 VARCHAR(255),
OPTION4 VARCHAR(255),
CORRECTANS VARCHAR(255),
CATID BIGINT(8),
PACKAGEID DOUBLE,
DIFFICULTY VARCHAR(16),
PRIMARY KEY(QID, PACKAGEID));

CREATE TABLE SIQUOIA.USERPROFILE(
U_ID INT NOT NULL AUTO_INCREMENT,
DISPLAYNAME VARCHAR(32),
EMAIL VARCHAR(32),
TOKENS BIGINT(8),
USERSTATUS INT,
CURRENTQSET BIGINT(8),
SCORE BIGINT(8),
RANK BIGINT(8),
PRIMARY KEY(U_ID, CURRENTQSET));


