INSERT INTO SIQUOIA.CATEGORY(CAT1NAME) VALUES ('SCIENCE');
INSERT INTO SIQUOIA.SUBCAT(CAT1ID, CAT2NAME) VALUES (1, 'MATH');
INSERT INTO SIQUOIA.SUBSUBCAT(CATID1, CATID2, CAT3NAME) VALUES (1, 1, 'ALGEBRA');