DROP TABLE SIQUOIA.AUTHENTICATION;
DROP TABLE SIQUOIA.QUESTION;
DROP TABLE SIQUOIA.USERPROFILE;
DROP TABLE SIQUOIA.CATEGORY;
DROP TABLE SIQUOIA.SUBCAT;
DROP TABLE SIQUOIA.SUBSUBCAT;

CREATE TABLE SIQUOIA.AUTHENTICATION(
ID INT NOT NULL AUTO_INCREMENT, 
USERNAME VARCHAR(32),
USERPASSWORD VARCHAR(32),
ADMIN BOOL,
PRIMARY KEY(ID));

CREATE TABLE SIQUOIA.QUESTION(
QID INT NOT NULL AUTO_INCREMENT,
CONTENT VARCHAR(255),
OPTION1 VARCHAR(255),
OPTION2 VARCHAR(255),
OPTION3 VARCHAR(255),
OPTION4 VARCHAR(255),
CORRECTANS VARCHAR(255),
CATID1 INT,
CATID2 INT,
CATID3 INT,
CATNAME VARCHAR(255),
DIFFICULTY VARCHAR(16),
PRIMARY KEY(QID));

CREATE TABLE SIQUOIA.USERPROFILE(
UID INT,
DISPLAYNAME VARCHAR(32),
EMAIL VARCHAR(32),
TOKENS INT,
USERSTATUS INT,
CATID1 INT,
CATID2 INT,
CATID3 INT,
CURRENTQSET VARCHAR(255),
SCORE INT,
RANK INT,
FOREIGN KEY(UID) REFERENCES SIQUOIA.AUTHENTICATION(ID));

CREATE TABLE SIQUOIA.CATEGORY(
CATID INT NOT NULL AUTO_INCREMENT,
CAT1NAME VARCHAR(255),
PRIMARY KEY(CATID));

CREATE TABLE SIQUOIA.SUBCAT(
CAT1ID INT,
CAT2ID INT NOT NULL AUTO_INCREMENT,
CAT2NAME VARCHAR(255),
PRIMARY KEY(CAT2ID),
FOREIGN KEY (CAT1ID) REFERENCES SIQUOIA.CATEGORY(CATID));

CREATE TABLE SIQUOIA.SUBSUBCAT(
CATID1 INT,
CATID2 INT,
CATID3 INT NOT NULL AUTO_INCREMENT,
CAT3NAME VARCHAR(255),
PRIMARY KEY(CATID3),
FOREIGN KEY(CATID1, CATID2) REFERENCES SIQUOIA.SUBCAT(CAT1ID, CAT2ID));
